### ISSUE TITLE
import error:  No module named 'ueyeh'

### ISSUE THREAD

**Issue by jverlie** [cihologramas/pyueye#12]
Since I'm using anaconda's python 3.6, I ported this repository to python 3 using '2to3'.
The installation completed fine (driver and git branch 4.82).
However I cannot get the example code to run.
When I try to `import ueye` I get the following modulenotfounderror:
```
 File "/home/jverlie/anaconda3/lib/python3.6/site-packages/ueye/__init__.py", line 36, in <module>
    from ueyeh import *
ModuleNotFoundError: No module named 'ueyeh'
``` 
What am I doing wrong?

**Comment by ramezquitao** [comment]
I'm sorry but unfortunately we are using the pyueye only in python 2. We have planned to port it to python 3, but we haven't got the time.

Maybe you can check the ueye/__init__.py and see if the way the import is being made is not compatible with python 3.
